In [ ]:
import numpy as np
import pylab as pl
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, f1_score, precision_score, recall_score

In [ ]:
from google.colab import files
uploades = files.upload()

Saving predic_tabel.csv to predic_tabel.csv


In [ ]:
df=pd.read_csv('predic_tabel.csv')
df.head()

No  Usia Jenis_Kelamin Merokok Bekerja Rumah_Tangga Aktivitas_Begadang  \
0   1   Tua          Pria   Pasif   Tidak           Ya                 Ya   
1   2   Tua          Pria   Aktif   Tidak           Ya                 Ya   
2   3  Muda          Pria   Aktif   Tidak           Ya                 Ya   
3   4   Tua          Pria   Aktif      Ya        Tidak              Tidak   
4   5  Muda        Wanita   Pasif      Ya        Tidak              Tidak   

  Aktivitas_Olahraga Asuransi Penyakit_Bawaan  Hasil  
0             Sering      Ada           Tidak     Ya  
1             Jarang      Ada             Ada  Tidak  
2             Jarang      Ada           Tidak  Tidak  
3             Jarang      Ada             Ada  Tidak  
4             Sering    Tidak             Ada     Ya

In [ ]:
df.drop(['No', 'Jenis_Kelamin', 'Bekerja', 'Rumah_Tangga', 'Asuransi'], axis=1, inplace=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   Usia                30000 non-null  object
 1   Merokok             30000 non-null  object
 2   Aktivitas_Begadang  30000 non-null  object
 3   Aktivitas_Olahraga  30000 non-null  object
 4   Penyakit_Bawaan     30000 non-null  object
 5   Hasil               30000 non-null  object
dtypes: object(6)
memory usage: 1.4+ MB


In [ ]:
labelencoder = LabelEncoder()
df['Usia'] = labelencoder.fit_transform(df['Usia'])
df['Merokok'] = labelencoder.fit_transform(df['Merokok'])
df['Aktivitas_Begadang'] = labelencoder.fit_transform(df['Aktivitas_Begadang'])
df['Aktivitas_Olahraga'] = labelencoder.fit_transform(df['Aktivitas_Olahraga'])
df['Penyakit_Bawaan'] = labelencoder.fit_transform(df['Penyakit_Bawaan'])
df['Hasil'] = labelencoder.fit_transform(df['Hasil'])

In [ ]:
df.head()

Usia  Merokok  Aktivitas_Begadang  Aktivitas_Olahraga  Penyakit_Bawaan  \
0     1        1                   1                   1                1   
1     1        0                   1                   0                0   
2     0        0                   1                   0                1   
3     1        0                   0                   0                0   
4     0        1                   0                   1                0   

   Hasil  
0      1  
1      0  
2      0  
3      0  
4      1

In [ ]:
X = df[['Usia', 'Merokok', 'Aktivitas_Begadang', 'Aktivitas_Olahraga', 'Penyakit_Bawaan']]
y = df['Hasil']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=0)

In [ ]:
sc = MinMaxScaler(feature_range=(0, 1))

X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

print(X_train, "\n")
print(X_test, "\n")

[[0. 0. 1. 0. 1.]
 [1. 1. 0. 1. 0.]
 [0. 0. 1. 0. 1.]
 ...
 [1. 0. 1. 0. 0.]
 [1. 1. 0. 1. 1.]
 [0. 1. 0. 1. 0.]] 

[[1. 0. 1. 0. 0.]
 [1. 1. 0. 1. 0.]
 [1. 0. 0. 0. 0.]
 ...
 [1. 0. 1. 0. 0.]
 [0. 0. 1. 0. 1.]
 [1. 0. 0. 0. 1.]] 



In [ ]:
clf = DecisionTreeClassifier(criterion="entropy", max_depth=3)

In [ ]:
clf = clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)

In [ ]:
print("Classification Report : \n", classification_report(y_test, y_pred))
print("F1 Score : \n", f1_score(y_test, y_pred))
print("Precision Score : \n", precision_score(y_test, y_pred))
print("Recall Score : \n", recall_score(y_test, y_pred))
print("Accuracy Score : \n", accuracy_score(y_test, y_pred))

Classification Report : 
               precision    recall  f1-score   support

           0       0.84      1.00      0.91      3180
           1       1.00      0.78      0.88      2820

    accuracy                           0.90      6000
   macro avg       0.92      0.89      0.90      6000
weighted avg       0.91      0.90      0.90      6000

F1 Score : 
 0.878727634194831
Precision Score : 
 1.0
Recall Score : 
 0.7836879432624113
Accuracy Score : 
 0.8983333333333333
